name: flutter_launcher_icons
description: A package which simplifies the task of updating your Flutter app's launcher icon.
version: 3.1.6
homepage: https://github.com/apps-auth/flutter_launcher_icons

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  args: ">=2.7.0 <3.0.0"
  checked_yaml: ^2.0.3
  cli_util: ^0.4.1

  image: ">=4.5.4 <5.0.0"
  json_annotation: ^4.9.0
  path: ">=1.9.1 <2.0.0"
  yaml: ">=3.1.3 <4.0.0"

dev_dependencies:
  # Needed by build_version
  build_runner: ^2.4.12
  # https://pub.dev/packages/build_version
  build_version: ^2.1.1
  json_serializable: ^6.10.0
  mockito: ^5.4.4
  test: ^1.25.8
  test_descriptor: ^2.0.1
